CREATE TABLE SECURITY (
EMPLOYEE_ID NUMBER(6,0) PRIMARY KEY NOT NULL,
SEC_ID VARCHAR2(20) NOT NULL,
SEC_PASSWORD VARCHAR2(10) NOT NULL,
SEC_STATUS CHAR(1) NOT NULL,

CONSTRAINT emp_emp_id_fk
    FOREIGN KEY (employee_id) REFERENCES EMPLOYEES,
CONSTRAINT emp_sec_status_ck
    CHECK (SEC_STATUS IN ('A', 'I'))
);